### PR TITLE
Building coffeeshop page

### PR DESCRIPTION
**Pull request by Najeeba-Qarqin**
Annotation 2024-05-29 111949
This is a product landing page about a coffee shop created by using HTML and styled by using CSS its a responsive web page.

### CODE REVIEW

**Comment by Najeeba-Qarqin** [comment]
@ahzamir I have finished the product landing page project please check out.

**Comment by Najeeba-Qarqin** [comment]
@ahzamir I'm waiting for your feedback.

**Comment by Najeeba-Qarqin** [comment]
@Breshna786 Share your feedback please.

**Comment by Najeeba-Qarqin** [comment]
@breshna786 share your feedback please.

**Comment by Najeeba-Qarqin** [comment]
@Breshna Andar786  share your feedback please.

**Comment by Najeeba-Qarqin** [comment]
@BreshnaAndar786 please share your feedback.

**Comment by ahzamir** [comment]
@Najeeba-Qarqin 

- Your project does not have Linters Config, please add the linters first then ask for a re-review.

**Comment by Najeeba-Qarqin** [comment]
@ahzamir Please review my project.

**Comment by Najeeba-Qarqin** [comment]
@ahzamir I added the linter file.

**Comment by Najeeba-Qarqin** [comment]
@ahzamir please review my project.

**Comment by Najeeba-Qarqin** [comment]
@ahzamir I'm waiting for your feedback.

**Review by ahzamir — APPROVED** [review]
### Hi @Najeeba-Qarqin 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- Wow amazing project with an impressive design implemented, I really appreciate your work and passion on this project.

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍

UntitledProject-ezgif com-video-to-gif-converter



# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Product Landing Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
